#!/usr/bin/env python2

import contextlib
import fnmatch
import glob
import os
import shutil
import subprocess


DSTDIR = "./tmp"
ARCHS = [
    ("darwin", "amd64", "osx64", "tgz"),
    ("windows", "amd64", "windows64", "zip"),
    ("linux", "amd64", "linux64", "tgz"),
    ("linux", "arm", "linuxARM", "tgz"),
    ("netbsd", "amd64", "netbsd64", "tgz"),
    ("netbsd", "arm", "netbsdARM", "tgz"),
    ("openbsd", "amd64", "openbsd64", "tgz"),
]

def install_dependencies():
    print("installing dependencies")
    deps = ['github.com/GeertJohan/go.rice',
            'github.com/GeertJohan/go.rice/rice',
            'github.com/cortesi/modd',
            'github.com/dustin/go-humanize',
            'github.com/goji/httpauth',
            'github.com/gorilla/websocket',
            'github.com/juju/ratelimit',
            'github.com/mitchellh/go-homedir',
            'github.com/toqueteos/webbrowser',
            'gopkg.in/alecthomas/kingpin.v2']

    for dep in deps:
        subprocess.check_call(["go", "get", dep])

def cleanrice(directory):
    for root, dirs, files in os.walk(directory):
        for basename in files:
            if basename.endswith("rice-box.go"):
                    filename = os.path.join(root, basename)
                    print "\t", filename
                    os.unlink(filename)


@contextlib.contextmanager
def chdir(newdir):
    curdir = os.getcwd()
    try:
        os.chdir(newdir)
        yield
    finally:
        os.chdir(curdir)


def version():
    print "Installing locally"
    subprocess.call(["go", "install", "./cmd/devd"])
    p = subprocess.Popen(["devd", "--version"], stderr=subprocess.PIPE)
    return p.communicate()[1].strip()


def build(vers, goos, goarch, name, archive):
    dst = os.path.join(DSTDIR, "devd-%s-%s"%(vers, name))
    print "building to ", dst
    for f in glob.glob(dst + "*"):
        if os.path.isdir(f):
            shutil.rmtree(f)
        else:
            os.unlink(f)
    os.makedirs(dst)
    env = os.environ.copy()
    env["GOOS"] = goos
    env["GOARCH"] = goarch
    subprocess.check_call(
        [
            "go", "build",
            "-o", os.path.join(dst, "devd"),
            "./cmd/devd"
        ],
        env = env
    )
    if archive == "tgz":
        print "\tmaking .tgz"
        subprocess.Popen(
            ["tar", "-czvf", dst + ".tgz", dst],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        ).communicate()
    elif archive == "zip":
        print "\tmaking .zip"
        subprocess.Popen(
            ["zip", "-r", dst + ".zip", dst],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        ).communicate()


def main():
    install_dependencies()

    print "Making static inclusions..."
    subprocess.call(["rice", "embed-go"])
    with chdir("livereload"):
        subprocess.call(["rice", "embed-go"])

    v = version()
    print "Version is: ", v

    for i in ARCHS:
        build(v, *i)

    print "Cleaning static inclusions..."
    cleanrice(".")


main()
