**/*.go livereload/*.js templates/*.html !vendor/** {
    prep: go test @dirmods
}

**/*.go livereload/*.js templates/*.html !**/*_test.go {
    prep: go install ./cmd/devd
    daemon +sigterm: devd -ml ./tmp
}
