version: 2

project_name: devd

builds:
  - id: devd-build
    main: ./cmd/devd
    binary: devd
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    targets:
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_386
      - linux_amd64
      - linux_arm
      - netbsd_amd64
      - netbsd_arm
      - openbsd_amd64
      - freebsd_amd64
    overrides:
      - goos: linux
        flags:
          - -trimpath
          - -tags=osusergo,netgo
        ldflags:
          - -s -w

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
