name: CI

on:
  push:
    branches:
    - master
  pull_request:
  # enable manual trigger
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: go test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - name:
      run: |
        go test -v -race ./...
        go run ./cmd/devd --help
